sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jbaxtron/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jbaxtron/docker-react npm run test